export type Grant = {
  id: string;
  title: string;
  organization: string;
  category: string;
  amountMin: number;
  amountMax: number;
  applicationStart: string; // ISO date
  applicationEnd: string;
  target: string;
  description: string;
  url?: string;
  region?: string;
  custom?: boolean;
};

export const CATEGORIES = [
  "子ども・教育",
  "環境・自然",
  "福祉・医療",
  "地域振興",
  "災害支援",
  "文化・芸術",
  "国際協力",
] as const;

export const REGIONS = [
  "全国",
  "北海道",
  "東北",
  "関東",
  "東京",
  "中部",
  "東海",
  "関西",
  "中国",
  "四国",
  "九州",
  "沖縄",
] as const;

export const getGrantRegion = (g: Grant): string => {
  if (g.region) return g.region;
  const src = `${g.organization} ${g.target}`;
  for (const r of REGIONS) {
    if (r !== "全国" && src.includes(r)) return r;
  }
  return "全国";
};

// ============================================================
// 実在する助成金・補助金プログラム（公式サイトURL付き）
// 掲載しているのは、公式ホームページの存在が確認できたプログラムのみです。
// 募集時期・金額は年度により変動します。最新情報は必ず公式サイトでご確認ください。
// ============================================================
export const GRANTS: Grant[] = [
  {
    id: "g-nippon-foundation",
    title: "日本財団 助成事業",
    organization: "公益財団法人 日本財団",
    category: "福祉・医療",
    amountMin: 500_000,
    amountMax: 100_000_000,
    applicationStart: "2026-08-01",
    applicationEnd: "2026-09-30",
    target: "NPO法人・公益法人・任意団体等",
    description: "海洋、社会福祉、教育、災害復興など幅広い分野の公益活動を支援。※例年8〜10月に翌年度助成の公募。詳細は公式サイトへ。",
    url: "https://www.nippon-foundation.or.jp/grant_application",
    region: "全国",
  },
  {
    id: "g-wam",
    title: "WAM助成（社会福祉振興助成事業）",
    organization: "独立行政法人 福祉医療機構（WAM）",
    category: "福祉・医療",
    amountMin: 500_000,
    amountMax: 9_000_000,
    applicationStart: "2026-01-06",
    applicationEnd: "2026-02-06",
    target: "NPO法人・社会福祉法人・一般社団法人等",
    description: "地域連携活動や全国的・広域的モデル活動を支援。※例年1〜2月に公募。詳細は公式サイトへ。",
    url: "https://www.wam.go.jp/hp/cat/wamjyosei/",
    region: "全国",
  },
  {
    id: "g-toyota",
    title: "トヨタ財団 国内助成プログラム",
    organization: "公益財団法人 トヨタ財団",
    category: "地域振興",
    amountMin: 1_000_000,
    amountMax: 8_000_000,
    applicationStart: "2026-04-01",
    applicationEnd: "2026-06-05",
    target: "NPO・任意団体・研究者等",
    description: "「未来の担い手と創造する持続可能な地域社会」をテーマに支援。※例年4〜6月に公募。",
    url: "https://www.toyotafound.or.jp/domestic/",
    region: "全国",
  },
  {
    id: "g-akaihane",
    title: "赤い羽根「令和のいのち・くらしを守る」活動応援助成",
    organization: "社会福祉法人 中央共同募金会",
    category: "福祉・医療",
    amountMin: 100_000,
    amountMax: 3_000_000,
    applicationStart: "2026-05-01",
    applicationEnd: "2026-06-30",
    target: "NPO・ボランティア団体・社会福祉法人等",
    description: "地域における福祉・生活支援活動を幅広く支援。詳細は公式サイトへ。",
    url: "https://www.akaihane.or.jp/",
    region: "全国",
  },
  {
    id: "g-panasonic",
    title: "Panasonic NPO/NGOサポートファンド for SDGs",
    organization: "パナソニック ホールディングス株式会社",
    category: "国際協力",
    amountMin: 500_000,
    amountMax: 2_000_000,
    applicationStart: "2026-06-01",
    applicationEnd: "2026-07-31",
    target: "NPO/NGO法人",
    description: "SDGs達成に向けた社会課題解決に取り組むNPO/NGOの組織基盤強化を支援。※例年6〜7月に公募。",
    url: "https://holdings.panasonic/jp/corporate/sustainability/citizenship/pnnf.html",
    region: "全国",
  },
  {
    id: "g-7midori",
    title: "セブン-イレブン記念財団 環境市民活動助成",
    organization: "一般財団法人 セブン-イレブン記念財団",
    category: "環境・自然",
    amountMin: 500_000,
    amountMax: 4_000_000,
    applicationStart: "2026-10-01",
    applicationEnd: "2026-11-15",
    target: "NPO法人・市民団体",
    description: "自然環境の保護・保全、環境教育活動などを支援。活動助成・自立事業助成など複数枠あり。",
    url: "https://www.7midori.org/josei/",
    region: "全国",
  },
  {
    id: "g-kirin",
    title: "キリン・地域のちから応援事業",
    organization: "公益財団法人 キリン福祉財団",
    category: "地域振興",
    amountMin: 100_000,
    amountMax: 300_000,
    applicationStart: "2026-09-01",
    applicationEnd: "2026-10-31",
    target: "ボランティア団体・NPO",
    description: "地域社会の福祉向上を目的とする市民活動を支援。※例年秋に公募。",
    url: "https://www.kirinholdings.com/jp/purpose/foundation/",
    region: "全国",
  },
  {
    id: "g-daiwa",
    title: "大和証券福祉財団 ボランティア活動助成",
    organization: "公益財団法人 大和証券福祉財団",
    category: "福祉・医療",
    amountMin: 100_000,
    amountMax: 300_000,
    applicationStart: "2026-06-01",
    applicationEnd: "2026-07-31",
    target: "ボランティア団体",
    description: "高齢者・障がい者・子どもへの福祉ボランティア活動を支援。",
    url: "https://www.daiwa-grp.jp/dsf/",
    region: "全国",
  },
  {
    id: "g-24hourtv",
    title: "24時間テレビチャリティー委員会 福祉車両寄贈・福祉支援",
    organization: "公益社団法人 24時間テレビチャリティー委員会",
    category: "福祉・医療",
    amountMin: 1_000_000,
    amountMax: 10_000_000,
    applicationStart: "2026-01-15",
    applicationEnd: "2026-03-31",
    target: "社会福祉法人・NPO法人等",
    description: "福祉車両の寄贈、施設整備、災害復興支援など。",
    url: "https://www.24hourtv.or.jp/",
    region: "全国",
  },
  {
    id: "g-yamato",
    title: "ヤマト福祉財団 障がい者福祉助成",
    organization: "公益財団法人 ヤマト福祉財団",
    category: "福祉・医療",
    amountMin: 100_000,
    amountMax: 5_000_000,
    applicationStart: "2026-09-15",
    applicationEnd: "2026-11-15",
    target: "障がい者支援団体・作業所等",
    description: "障がい者の自立と社会参加を支援する事業に対する助成。",
    url: "https://www.yamato-fukushi.jp/",
    region: "全国",
  },
  {
    id: "g-mufg-env",
    title: "三菱UFJ環境財団 研究助成",
    organization: "公益財団法人 三菱UFJ環境財団",
    category: "環境・自然",
    amountMin: 300_000,
    amountMax: 1_000_000,
    applicationStart: "2026-04-01",
    applicationEnd: "2026-06-30",
    target: "研究者・NPO",
    description: "環境保全に関する研究・活動を支援。",
    url: "https://www.muef.or.jp/",
    region: "全国",
  },
  {
    id: "g-sompo-env",
    title: "SOMPO環境財団 環境保全プロジェクト助成",
    organization: "公益財団法人 SOMPO環境財団",
    category: "環境・自然",
    amountMin: 200_000,
    amountMax: 2_000_000,
    applicationStart: "2026-05-01",
    applicationEnd: "2026-07-15",
    target: "NPO・環境団体",
    description: "国内の環境NPOや若手研究者を対象とした活動助成。",
    url: "https://www.sompo-ef.org/",
    region: "全国",
  },
  {
    id: "g-yahoo",
    title: "Yahoo!基金 活動支援助成",
    organization: "公益財団法人 Yahoo!基金",
    category: "災害支援",
    amountMin: 100_000,
    amountMax: 3_000_000,
    applicationStart: "2026-02-01",
    applicationEnd: "2026-03-31",
    target: "NPO・ボランティア団体",
    description: "防災・減災、被災地支援、次世代育成などの活動を支援。",
    url: "https://kikin.yahoo.co.jp/",
    region: "全国",
  },
  {
    id: "g-coop-sasaeai",
    title: "コープ共済 地域ささえあい助成",
    organization: "日本コープ共済生活協同組合連合会",
    category: "地域振興",
    amountMin: 100_000,
    amountMax: 2_000_000,
    applicationStart: "2026-01-15",
    applicationEnd: "2026-03-15",
    target: "生協・NPO・市民団体",
    description: "生協と市民団体が協働して行う、くらしと地域を守る活動を支援。",
    url: "https://coopkyosai.coop/about/csr/socialwelfare/",
    region: "全国",
  },
  {
    id: "g-aeon-env",
    title: "イオン環境財団 環境活動助成",
    organization: "公益財団法人 イオン環境財団",
    category: "環境・自然",
    amountMin: 500_000,
    amountMax: 3_000_000,
    applicationStart: "2026-05-01",
    applicationEnd: "2026-06-30",
    target: "NPO・市民団体・研究者",
    description: "国内外の環境保全活動・生物多様性保全を支援。",
    url: "https://www.aeon.info/ef/",
    region: "全国",
  },
  {
    id: "g-mitsui-env",
    title: "三井物産環境基金 活動助成",
    organization: "三井物産株式会社",
    category: "環境・自然",
    amountMin: 1_000_000,
    amountMax: 20_000_000,
    applicationStart: "2026-04-01",
    applicationEnd: "2026-05-31",
    target: "NPO・NGO・大学等",
    description: "地球環境問題の解決に取り組む活動を支援。",
    url: "https://www.mitsui.com/jp/ja/sustainability/contribution/environment/fund/",
    region: "全国",
  },
  {
    id: "g-benesse-kodomo",
    title: "ベネッセこども基金 経済的困難を抱える子どもの学び支援活動助成",
    organization: "公益財団法人 ベネッセこども基金",
    category: "子ども・教育",
    amountMin: 500_000,
    amountMax: 8_000_000,
    applicationStart: "2026-09-01",
    applicationEnd: "2026-10-31",
    target: "NPO法人・一般社団法人等",
    description: "経済的困難を抱える子どもの学びを支える活動を助成。",
    url: "https://benesse-kodomokikin.or.jp/",
    region: "全国",
  },
  {
    id: "g-docomo-mcfund",
    title: "ドコモ市民活動団体助成事業",
    organization: "公益財団法人 モバイル・コミュニケーション・ファンド",
    category: "子ども・教育",
    amountMin: 300_000,
    amountMax: 700_000,
    applicationStart: "2026-02-01",
    applicationEnd: "2026-03-31",
    target: "NPO・任意団体",
    description: "子どもの健全な育成を支援する市民活動団体への助成。",
    url: "https://www.mcfund.or.jp/",
    region: "全国",
  },
  {
    id: "g-mitsubishi-zaidan",
    title: "三菱財団 社会福祉事業並びに研究助成",
    organization: "公益財団法人 三菱財団",
    category: "福祉・医療",
    amountMin: 1_000_000,
    amountMax: 5_000_000,
    applicationStart: "2026-01-05",
    applicationEnd: "2026-02-10",
    target: "社会福祉法人・NPO・研究者",
    description: "先駆的・実験的な社会福祉事業や研究への助成。",
    url: "https://www.mitsubishi-zaidan.jp/",
    region: "全国",
  },
  {
    id: "g-erca-jfge",
    title: "地球環境基金 助成金",
    organization: "独立行政法人 環境再生保全機構",
    category: "環境・自然",
    amountMin: 500_000,
    amountMax: 12_000_000,
    applicationStart: "2026-11-15",
    applicationEnd: "2026-12-20",
    target: "NPO・NGO",
    description: "民間団体が行う環境保全活動への助成。国内・海外の枠あり。",
    url: "https://www.erca.go.jp/jfge/",
    region: "全国",
  },
  {
    id: "g-jpf",
    title: "国際交流基金 助成プログラム",
    organization: "独立行政法人 国際交流基金",
    category: "国際協力",
    amountMin: 500_000,
    amountMax: 10_000_000,
    applicationStart: "2026-10-01",
    applicationEnd: "2026-12-01",
    target: "NPO・大学・文化団体",
    description: "文化芸術交流・海外日本語教育・日本研究等への助成。",
    url: "https://www.jpf.go.jp/j/program/",
    region: "全国",
  },
  {
    id: "g-sumitomo-kodomo",
    title: "住友生命こども文化財団 児童福祉助成",
    organization: "公益財団法人 住友生命健康財団",
    category: "子ども・教育",
    amountMin: 200_000,
    amountMax: 1_000_000,
    applicationStart: "2026-06-01",
    applicationEnd: "2026-07-31",
    target: "NPO・社会福祉法人",
    description: "子どもの健やかな成長を支える活動を支援。",
    url: "https://www.skzaidan.or.jp/",
    region: "全国",
  },
  {
    id: "g-soroptimist",
    title: "ソロプチミスト日本財団 社会貢献ボランティア基金",
    organization: "公益財団法人 ソロプチミスト日本財団",
    category: "福祉・医療",
    amountMin: 200_000,
    amountMax: 1_000_000,
    applicationStart: "2026-03-01",
    applicationEnd: "2026-05-31",
    target: "NPO・ボランティア団体",
    description: "女性と女児の地位向上、社会貢献活動を支援。",
    url: "https://www.sifjapan.org/",
    region: "全国",
  },
  {
    id: "g-mizuho-ewf",
    title: "みずほ教育福祉財団 老後を豊かにするボランティア活動資金助成",
    organization: "公益財団法人 みずほ教育福祉財団",
    category: "福祉・医療",
    amountMin: 100_000,
    amountMax: 500_000,
    applicationStart: "2026-02-15",
    applicationEnd: "2026-04-15",
    target: "高齢者福祉ボランティア団体",
    description: "高齢者を対象としたボランティア活動団体に対する備品購入等の助成。",
    url: "https://www.mizuho-ewf.or.jp/",
    region: "全国",
  },
  {
    id: "g-sompo-wf",
    title: "SOMPO福祉財団 NPO基盤強化資金助成",
    organization: "公益財団法人 SOMPO福祉財団",
    category: "福祉・医療",
    amountMin: 300_000,
    amountMax: 3_000_000,
    applicationStart: "2026-07-01",
    applicationEnd: "2026-08-31",
    target: "NPO法人",
    description: "認定NPO取得や組織基盤強化のための資金助成。",
    url: "https://www.sompo-wf.org/",
    region: "全国",
  },
  {
    id: "g-jinsha",
    title: "年賀寄付金による社会貢献事業助成",
    organization: "日本郵便株式会社",
    category: "福祉・医療",
    amountMin: 500_000,
    amountMax: 5_000_000,
    applicationStart: "2026-09-05",
    applicationEnd: "2026-11-10",
    target: "社会福祉法人・NPO法人等",
    description: "お年玉付郵便葉書等の寄付金を活用した社会貢献事業への配分。",
    url: "https://www.post.japanpost.jp/kifu/",
    region: "全国",
  },
  {
    id: "g-kamenori",
    title: "かめのり財団 日本・アジア青少年サイエンス交流事業",
    organization: "公益財団法人 かめのり財団",
    category: "国際協力",
    amountMin: 500_000,
    amountMax: 3_000_000,
    applicationStart: "2026-05-01",
    applicationEnd: "2026-07-15",
    target: "NPO・学校・大学",
    description: "アジアの青少年交流・国際協力活動を支援。",
    url: "https://www.kamenori.jp/",
    region: "全国",
  },
  {
    id: "g-suzaki",
    title: "洲崎福祉財団 一般助成",
    organization: "公益財団法人 洲崎福祉財団",
    category: "福祉・医療",
    amountMin: 300_000,
    amountMax: 2_000_000,
    applicationStart: "2026-05-01",
    applicationEnd: "2026-06-30",
    target: "NPO法人・社会福祉法人",
    description: "障がい児・者の支援活動、地域福祉活動への助成。",
    url: "https://swf.or.jp/",
    region: "全国",
  },
  {
    id: "g-mazda",
    title: "マツダ財団 市民活動支援",
    organization: "公益財団法人 マツダ財団",
    category: "地域振興",
    amountMin: 200_000,
    amountMax: 500_000,
    applicationStart: "2026-04-01",
    applicationEnd: "2026-05-31",
    target: "市民団体・NPO",
    description: "青少年の健全育成、地域社会活性化のための市民活動を支援。",
    url: "https://mzaidan.mazda.co.jp/",
    region: "中国",
  },
  {
    id: "g-shiseido",
    title: "資生堂社会福祉事業財団 女性福祉助成",
    organization: "公益財団法人 資生堂社会福祉事業財団",
    category: "福祉・医療",
    amountMin: 100_000,
    amountMax: 1_000_000,
    applicationStart: "2026-08-01",
    applicationEnd: "2026-09-30",
    target: "社会福祉法人・NPO",
    description: "女性と子どもの福祉向上に取り組む活動への助成。",
    url: "https://www.zaidan.shiseido.co.jp/",
    region: "全国",
  },
  {
    id: "g-syaanken",
    title: "日工組社会安全研究財団 一般研究助成",
    organization: "公益財団法人 日工組社会安全研究財団",
    category: "地域振興",
    amountMin: 500_000,
    amountMax: 3_000_000,
    applicationStart: "2026-06-01",
    applicationEnd: "2026-07-31",
    target: "研究者・NPO",
    description: "犯罪・非行の防止など社会安全に関する研究・実践活動を支援。",
    url: "https://www.syaanken.or.jp/",
    region: "全国",
  },
  {
    id: "g-musubie",
    title: "むすびえ・こども食堂基金",
    organization: "認定NPO法人 全国こども食堂支援センター・むすびえ",
    category: "子ども・教育",
    amountMin: 50_000,
    amountMax: 1_000_000,
    applicationStart: "2026-04-01",
    applicationEnd: "2026-05-31",
    target: "こども食堂・地域団体",
    description: "全国のこども食堂への運営助成・物品支援。",
    url: "https://musubie.org/",
    region: "全国",
  },
  {
    id: "g-toto-water",
    title: "TOTO水環境基金",
    organization: "TOTO株式会社",
    category: "環境・自然",
    amountMin: 500_000,
    amountMax: 1_000_000,
    applicationStart: "2026-09-01",
    applicationEnd: "2026-10-31",
    target: "NPO・市民団体",
    description: "地域の水環境保全・啓発活動、海外の水環境改善事業を支援。",
    url: "https://jp.toto.com/company/csr/environment/fund/",
    region: "全国",
  },
  {
    id: "g-astellas",
    title: "アステラス スターライトパートナー",
    organization: "アステラス製薬株式会社",
    category: "福祉・医療",
    amountMin: 300_000,
    amountMax: 1_500_000,
    applicationStart: "2026-06-01",
    applicationEnd: "2026-07-31",
    target: "NPO法人",
    description: "難病や慢性疾患を抱える子どもと家族を支援する活動を助成。",
    url: "https://www.astellas.com/jp/sustainability/community-activities",
    region: "全国",
  },
  {
    id: "g-hirose",
    title: "ヒロセ財団 社会貢献助成",
    organization: "公益財団法人 ヒロセ財団",
    category: "福祉・医療",
    amountMin: 500_000,
    amountMax: 5_000_000,
    applicationStart: "2026-04-01",
    applicationEnd: "2026-05-31",
    target: "NPO法人等",
    description: "社会福祉・青少年育成・災害復興等の分野への助成。",
    url: "https://hirose-fdn.or.jp/",
    region: "全国",
  },
  {
    id: "g-vpfj",
    title: "車両競技公益資金記念財団 社会福祉助成",
    organization: "公益財団法人 車両競技公益資金記念財団",
    category: "福祉・医療",
    amountMin: 500_000,
    amountMax: 3_000_000,
    applicationStart: "2026-11-01",
    applicationEnd: "2026-12-25",
    target: "社会福祉法人・NPO法人",
    description: "社会福祉施設等の整備・改修に対する助成。",
    url: "https://www.vpfj.or.jp/",
    region: "全国",
  },
  {
    id: "g-my-kokoro",
    title: "明治安田こころの健康財団 研究助成",
    organization: "公益財団法人 明治安田こころの健康財団",
    category: "福祉・医療",
    amountMin: 300_000,
    amountMax: 1_000_000,
    applicationStart: "2026-07-01",
    applicationEnd: "2026-09-30",
    target: "研究者・NPO",
    description: "心の健康・メンタルヘルスに関する調査研究への助成。",
    url: "https://www.my-kokoro.jp/",
    region: "全国",
  },
  {
    id: "g-sony-music",
    title: "ソニー音楽財団 こども音楽基金",
    organization: "公益財団法人 ソニー音楽財団",
    category: "文化・芸術",
    amountMin: 500_000,
    amountMax: 10_000_000,
    applicationStart: "2026-01-15",
    applicationEnd: "2026-02-28",
    target: "NPO・任意団体",
    description: "こどもたちの音楽を通じた学び・体験活動を支援。",
    url: "https://www.smf.or.jp/",
    region: "全国",
  },
  {
    id: "g-jt-npo",
    title: "JT NPO助成事業",
    organization: "日本たばこ産業株式会社",
    category: "地域振興",
    amountMin: 500_000,
    amountMax: 1_500_000,
    applicationStart: "2026-08-01",
    applicationEnd: "2026-09-30",
    target: "NPO法人",
    description: "自立支援と再挑戦を後押しする社会貢献活動への助成。",
    url: "https://www.jti.co.jp/csr/npo/index.html",
    region: "全国",
  },
  {
    id: "g-fujifilm-green",
    title: "富士フイルム・グリーンファンド",
    organization: "公益信託 富士フイルム・グリーンファンド",
    category: "環境・自然",
    amountMin: 300_000,
    amountMax: 2_000_000,
    applicationStart: "2026-01-10",
    applicationEnd: "2026-02-28",
    target: "NPO・研究者",
    description: "自然環境保全に関する市民活動・研究への助成。",
    url: "https://www.nacsj.or.jp/ffgf/",
    region: "全国",
  },
  {
    id: "g-tokyo-tomin",
    title: "東京都共同募金会 地域配分助成",
    organization: "社会福祉法人 東京都共同募金会",
    category: "地域振興",
    amountMin: 100_000,
    amountMax: 2_000_000,
    applicationStart: "2026-06-01",
    applicationEnd: "2026-07-31",
    target: "都内NPO・社会福祉法人",
    description: "東京都内の地域福祉活動・ボランティア活動への助成。",
    url: "https://www.tokyo-akaihane.or.jp/",
    region: "東京",
  },
  {
    id: "g-osaka-community",
    title: "大阪コミュニティ財団 各種助成プログラム",
    organization: "公益財団法人 大阪コミュニティ財団",
    category: "地域振興",
    amountMin: 100_000,
    amountMax: 3_000_000,
    applicationStart: "2026-09-01",
    applicationEnd: "2026-10-31",
    target: "NPO・市民団体",
    description: "関西を中心とした社会福祉・教育・文化・環境等多岐にわたる助成。",
    url: "https://www.osaka-community.or.jp/",
    region: "関西",
  },
  {
    id: "g-hokkaido-akaihane",
    title: "北海道共同募金会 じぶんの町を良くするしくみ助成",
    organization: "社会福祉法人 北海道共同募金会",
    category: "地域振興",
    amountMin: 100_000,
    amountMax: 1_000_000,
    applicationStart: "2026-05-01",
    applicationEnd: "2026-06-30",
    target: "道内NPO・地域団体",
    description: "北海道内の地域福祉・住民主体の活動を支援。",
    url: "https://www.akaihane-hokkaido.jp/",
    region: "北海道",
  },
  {
    id: "g-jica-partner",
    title: "JICA 草の根技術協力事業",
    organization: "独立行政法人 国際協力機構（JICA）",
    category: "国際協力",
    amountMin: 10_000_000,
    amountMax: 100_000_000,
    applicationStart: "2026-05-01",
    applicationEnd: "2026-06-30",
    target: "NPO・NGO・大学・地方自治体",
    description: "開発途上国の地域住民を対象とする国際協力事業を支援。",
    url: "https://www.jica.go.jp/activities/schemes/grass_roots/index.html",
    region: "全国",
  },
  {
    id: "g-jvoad",
    title: "災害NGO支援プログラム",
    organization: "特定非営利活動法人 全国災害ボランティア支援団体ネットワーク（JVOAD）",
    category: "災害支援",
    amountMin: 500_000,
    amountMax: 5_000_000,
    applicationStart: "2026-04-01",
    applicationEnd: "2026-12-28",
    target: "災害支援NPO・ボランティア団体",
    description: "災害時の被災者支援活動に取り組む団体を随時支援。",
    url: "https://jvoad.jp/",
    region: "全国",
  },
  {
    id: "g-geibunkyokai",
    title: "芸術文化振興基金 助成金",
    organization: "独立行政法人 日本芸術文化振興会",
    category: "文化・芸術",
    amountMin: 500_000,
    amountMax: 20_000_000,
    applicationStart: "2026-09-01",
    applicationEnd: "2026-10-15",
    target: "芸術団体・NPO",
    description: "舞台芸術・美術・伝統芸能・アマチュア文化活動などへの助成。",
    url: "https://www.ntj.jac.go.jp/kikin.html",
    region: "全国",
  },
  {
    id: "g-taiwa",
    title: "大和ハウス工業 エンドレス募金",
    organization: "大和ハウス工業株式会社",
    category: "福祉・医療",
    amountMin: 100_000,
    amountMax: 3_000_000,
    applicationStart: "2026-04-01",
    applicationEnd: "2026-05-31",
    target: "NPO・社会福祉法人",
    description: "こども・環境・災害復興支援分野の団体活動を支援。",
    url: "https://www.daiwahouse.com/sustainable/social/donation/",
    region: "全国",
  },
  {
    id: "g-nishimatsuya",
    title: "西松屋チェーン 子ども未来基金",
    organization: "株式会社 西松屋チェーン",
    category: "子ども・教育",
    amountMin: 100_000,
    amountMax: 1_000_000,
    applicationStart: "2026-06-01",
    applicationEnd: "2026-07-31",
    target: "NPO・子育て支援団体",
    description: "子どもと子育て家庭を支援する活動への助成。",
    url: "https://www.24028.jp/csr/",
    region: "全国",
  },
  {
    id: "g-jt-forest",
    title: "国土緑化推進機構 緑の募金公募事業",
    organization: "公益社団法人 国土緑化推進機構",
    category: "環境・自然",
    amountMin: 500_000,
    amountMax: 3_000_000,
    applicationStart: "2026-10-15",
    applicationEnd: "2026-11-30",
    target: "NPO・森林ボランティア団体",
    description: "国内外の森林整備・緑化活動、こどもの森づくり等を支援。",
    url: "https://www.green.or.jp/bokin/",
    region: "全国",
  },
  {
    id: "g-jrc-boshu",
    title: "日本赤十字社 災害義援金・救援活動助成",
    organization: "日本赤十字社",
    category: "災害支援",
    amountMin: 500_000,
    amountMax: 10_000_000,
    applicationStart: "2026-01-05",
    applicationEnd: "2026-12-28",
    target: "被災地支援団体",
    description: "災害時の救護・被災者支援活動に対する各種支援制度。",
    url: "https://www.jrc.or.jp/",
    region: "全国",
  },
];
