/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TsunaguriPreviewRouteImport } from './routes/tsunaguri-preview'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as ApiPublicHooksSyncJgrantsRouteImport } from './routes/api/public/hooks/sync-jgrants'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TsunaguriPreviewRoute = TsunaguriPreviewRouteImport.update({
  id: '/tsunaguri-preview',
  path: '/tsunaguri-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSyncJgrantsRoute =
  ApiPublicHooksSyncJgrantsRouteImport.update({
    id: '/api/public/hooks/sync-jgrants',
    path: '/api/public/hooks/sync-jgrants',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tsunaguri-preview': typeof TsunaguriPreviewRoute
  '/invite/$token': typeof InviteTokenRoute
  '/api/public/hooks/sync-jgrants': typeof ApiPublicHooksSyncJgrantsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tsunaguri-preview': typeof TsunaguriPreviewRoute
  '/invite/$token': typeof InviteTokenRoute
  '/api/public/hooks/sync-jgrants': typeof ApiPublicHooksSyncJgrantsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tsunaguri-preview': typeof TsunaguriPreviewRoute
  '/invite/$token': typeof InviteTokenRoute
  '/api/public/hooks/sync-jgrants': typeof ApiPublicHooksSyncJgrantsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/tsunaguri-preview'
    | '/invite/$token'
    | '/api/public/hooks/sync-jgrants'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/tsunaguri-preview'
    | '/invite/$token'
    | '/api/public/hooks/sync-jgrants'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/tsunaguri-preview'
    | '/invite/$token'
    | '/api/public/hooks/sync-jgrants'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TsunaguriPreviewRoute: typeof TsunaguriPreviewRoute
  InviteTokenRoute: typeof InviteTokenRoute
  ApiPublicHooksSyncJgrantsRoute: typeof ApiPublicHooksSyncJgrantsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tsunaguri-preview': {
      id: '/tsunaguri-preview'
      path: '/tsunaguri-preview'
      fullPath: '/tsunaguri-preview'
      preLoaderRoute: typeof TsunaguriPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-jgrants': {
      id: '/api/public/hooks/sync-jgrants'
      path: '/api/public/hooks/sync-jgrants'
      fullPath: '/api/public/hooks/sync-jgrants'
      preLoaderRoute: typeof ApiPublicHooksSyncJgrantsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TsunaguriPreviewRoute: TsunaguriPreviewRoute,
  InviteTokenRoute: InviteTokenRoute,
  ApiPublicHooksSyncJgrantsRoute: ApiPublicHooksSyncJgrantsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
